# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rdu7VehvYM3TgHTKcU08POJ2mg422395
"""

!pip install streamlit
import streamlit as st
import numpy as np
import pandas as pd
import joblib

# Load model + scaler
model = joblib.load('/content/heart_model.pkl')
scaler = joblib.load('/content/scaler.pkl')

# Column names
columns = [
    'age','sex','cp','trestbps','chol','fbs',
    'restecg','thalach','exang','oldpeak',
    'slope','ca','thal'
]

st.title("❤️ Heart Disease Prediction Dashboard")
st.write("Enter patient details:")

# Inputs
age = st.number_input("Age (20–80)", 20, 80, 63)
sex = st.selectbox("Sex (0=Female, 1=Male)", [0,1])
cp = st.selectbox("Chest Pain Type (0–3)", [0,1,2,3])
trestbps = st.number_input("Resting BP (90–200)", 90, 200, 145)
chol = st.number_input("Cholesterol (100–600)", 100, 600, 233)
fbs = st.selectbox("Fasting Blood Sugar >120 (0/1)", [0,1])
restecg = st.selectbox("Rest ECG (0–2)", [0,1,2])
thalach = st.number_input("Max Heart Rate (70–210)", 70, 210, 150)
exang = st.selectbox("Exercise Angina (0/1)", [0,1])
oldpeak = st.number_input("Oldpeak (0–6)", 0.0, 6.0, 2.3)
slope = st.selectbox("Slope (0–2)", [0,1,2])
ca = st.selectbox("CA (0–3)", [0,1,2,3])
thal = st.selectbox("Thal (1–3)", [1,2,3])

if st.button("Predict"):

    # Create DataFrame
    sample = pd.DataFrame([[age, sex, cp, trestbps, chol, fbs,
                            restecg, thalach, exang, oldpeak,
                            slope, ca, thal]], columns=columns)

    # One-hot encoding
    sample_encoded = pd.get_dummies(sample)

    # Align columns with training data
    sample_encoded = sample_encoded.reindex(columns=model.feature_names_in_, fill_value=0)

    # Scale continuous columns
    continuous_cols = ['age','trestbps','chol','thalach','oldpeak','ca']
    sample_encoded[continuous_cols] = scaler.transform(sample_encoded[continuous_cols])

    # Prediction
    pred = model.predict(sample_encoded)[0]
    prob = model.predict_proba(sample_encoded)[0][1]

    if pred == 1:
        st.error(f"⚠️ Disease Present (Confidence: {prob:.2%})")
    else:
        st.success(f"✅ No Disease (Confidence: {1-prob:.2%})")

    st.write("### Explanation:")
    st.write("This prediction is influenced by key clinical indicators such as heart rate, chest pain type, and ST depression.")